#!/bin/bash
# declarations.sh — Estimation declaration/default helpers.

bk_estimation_apply_declared_defaults() {
  BK_ESTIMATION_CURRENT_PACKAGE="${BK_ESTIMATION_CURRENT_PACKAGE:-${BK_ESTIMATION_DECLARED_CURRENT_PACKAGE:-}}"
  BK_ESTIMATION_FUTURE_PACKAGE="${BK_ESTIMATION_FUTURE_PACKAGE:-${BK_ESTIMATION_DECLARED_FUTURE_PACKAGE:-}}"
  BK_ESTIMATION_BASELINE_SYSTEM="${BK_ESTIMATION_BASELINE_SYSTEM:-${BK_ESTIMATION_DECLARED_BASELINE_SYSTEM:-}}"
  BK_ESTIMATION_BASELINE_EXP="${BK_ESTIMATION_BASELINE_EXP:-${BK_ESTIMATION_DECLARED_BASELINE_EXP:-}}"
  BK_ESTIMATION_FUTURE_SYSTEM="${BK_ESTIMATION_FUTURE_SYSTEM:-${BK_ESTIMATION_DECLARED_FUTURE_SYSTEM:-}}"
  BK_ESTIMATION_CURRENT_TARGET_NODES="${BK_ESTIMATION_CURRENT_TARGET_NODES:-${BK_ESTIMATION_DECLARED_CURRENT_TARGET_NODES:-}}"
  BK_ESTIMATION_FUTURE_TARGET_NODES="${BK_ESTIMATION_FUTURE_TARGET_NODES:-${BK_ESTIMATION_DECLARED_FUTURE_TARGET_NODES:-}}"
  export BK_ESTIMATION_CURRENT_PACKAGE
  export BK_ESTIMATION_FUTURE_PACKAGE
  export BK_ESTIMATION_BASELINE_SYSTEM
  export BK_ESTIMATION_BASELINE_EXP
  export BK_ESTIMATION_FUTURE_SYSTEM
  export BK_ESTIMATION_CURRENT_TARGET_NODES
  export BK_ESTIMATION_FUTURE_TARGET_NODES
}
